---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

chainflip:
  validator:
    source_url: https://github.com/chainflip-io/chainflip-backend/releases/download
    ports:
      p2p_port: 30334
      rpc_port: 9945
      prometheus_port: 9616
      engine_p2p_port: 8078
      command_server_port: 36079

promtail:
  service_identifier_suffix: promtail
  source_url: https://github.com/grafana/loki/releases/download
  file_extension: zip
  ports:
    http_listen_port:
      validator: 9086
      fullnode: 9088
    grpc_listen_port:
      validator: 9087
      fullnode: 9089
