---
# maintains ports, bianry or repo urls

org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
monitor_server_dns: monitor.encapsulate.xyz
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

chainflip:
  node:
    source_url: https://artifacts.chainflip.io
    ports:
      p2p_port: 30334
      rpc_port: 9945
      prometheus_port: 9616
  engine:
    source_url: https://artifacts.chainflip.io
    ports:
      engine_prometheus_port: 5566
      engine_p2p_port: 8078
      command_server_port: 36079

promtail:
  service_identifier_suffix: promtail
  source_url: https://github.com/grafana/loki/releases/download
  file_extension: zip
  ports:
    http_listen_port:
      validator: 9086
    grpc_listen_port:
      validator: 9087

process_exporter:
  service_identifier_suffix: process-exporter
  source_url: https://github.com/ncabatoff/process-exporter/releases/download
  file_extension: tar.gz
  ports:
    web_listen_address: 
      validator: 9257
