---
node_ufw_rules:
    - port: "{{ chainflip.validator.ports.p2p_port }}"
      proto: tcp
      rule: allow
      from: any
      comment: p2p_port

    - port: "{{ chainflip.validator.ports.prometheus_port }}"
      proto: tcp
      rule: allow
      from: "{{ monitor_server_dns }}"
      comment: prometheus_port
