---
- name: Copy binary and shared library files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    remote_src: true
    mode: "0755"
  loop:
    - { src: "{{ tmp_dir }}/{{ project }}/target/release/{{ engine_engine_default_binary_name }}", dest: "{{ engine_bin_dir }}/{{ service_identifier }}" }
    - src: "{{ tmp_dir }}/{{ project }}/target/release/{{ engine_shared_libraries_default_name[env][1] }}"
      dest: "{{ engine_lib_dir }}/{{ engine_shared_libraries_default_name[env][1] }}"
  notify:
    - Restart service

- name: Clean up the temporary repository directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ project }}"
    state: absent
