---
- name: Create a tmp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download and unarchive the binary
  ansible.builtin.unarchive:
    src: "{{ chainflip.engine.source_url }}/{{ chainflip.engine.version }}/chainflip-backend-bin.zip"
    dest: "{{ tmp_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy the binary file
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ service_identifier }}/artifacts/chainflip-backend-bin/{{ engine_engine_default_binary_name }}"
    dest: "{{ engine_bin_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"

- name: Fetch the engine service libraries
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ service_identifier }}/artifacts/chainflip-backend-bin/{{ item }}"
    dest: "{{ engine_lib_dir }}/{{ item }}"
    owner: root
    group: root
    force: true
    mode: "0755"
  loop: "{{ chainflip.engine.shared_libraries }}"
  notify:
    - Restart service

- name: Clean up the temporary files in /tmp
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: absent
