---
- name: Include the ufw rules vars file
  ansible.builtin.include_vars:
    file: vars/ufw_rules.yml

- name: Apply UFW rules
  ansible.builtin.include_tasks: tasks/apply_ufw_rules.yml
  loop: "{{ engine_ufw_rules }}"

- name: Include user creation task
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ engine_home_dir }}"
    directories: "{{ engine_directories }}"
    log_file_path: "{{ engine_log_file_path }}"

- name: Include download binary task
  ansible.builtin.include_tasks: download_binary.yml

- name: Copy engine configuration file
  ansible.builtin.template:
    src: "{{ env }}/settings.toml.j2"
    dest: "{{ engine_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service

- name: Fetch secrets from HCP Vault and save to files
  when: fetch_validator_keys | default(false) | bool
  block:
    - name: Fetch node key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ engine_node_key_file_name }}"
        secret_destination_path: "{{ engine_node_key_path }}"
        secret_type: key

    - name: Fetch signing key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ engine_signing_key_file_name }}"
        secret_destination_path: "{{ engine_signing_key_path }}"
        secret_type: key

    - name: Fetch ethereum private key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ engine_ethereum_private_key_file_name }}"
        secret_destination_path: "{{ engine_ethereum_private_key_path }}"
        secret_type: key

- name: Copy environment file
  ansible.builtin.template:
    src: "{{ env }}/general.env.j2"
    dest: "{{ engine_environment_general_file_path }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart service

- name: Copy node engine service file
  ansible.builtin.template:
    src: "{{ env }}/engine.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
