---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    chainflip:
      hosts:
        chainflip_node_host:
          ansible_host: validator.chainflip.mainnet.encapsulate.xyz
          type: node
        chainflip_engine_host:
          ansible_host: validator.chainflip.mainnet.encapsulate.xyz
          type: engine
