---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    chainflip:
      hosts:
        chainflip_node_host:
          ansible_host: validator.chainflip.testnet.encapsulate.xyz
          type: node
        chainflip_engine_host:
          ansible_host: validator.chainflip.testnet.encapsulate.xyz
          type: engine
