---
- name: Create system user with home and nologin
  ansible.builtin.user:
    name: "{{ service_identifier }}"
    system: true
    home: "{{ home }}"
    shell: /usr/sbin/nologin
    createhome: true
    state: present

- name: Allow passwordless sudo for user
  ansible.builtin.copy:
    content: "{{ service_identifier }} ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/{{ service_identifier }}
    owner: root
    group: root
    mode: "0440"
  when: allow_passwordless_sudo | default(false)

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0755"
  loop: "{{ directories }}"

- name: Create log file for the service
  ansible.builtin.file:
    path: "{{ log_file_path }}"
    state: touch
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
