---
- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
  loop:
    - make
    - build-essential
    - gcc
    - protobuf-compiler
    - cargo
    - rustup
    - pkg-config
    - libssl-dev
    - clang
    - cmake
    - jq
