---
- name: Ensure tmp directory exists
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: "1777"

- name: Clone the repository to /tmp
  ansible.builtin.git:
    repo: "{{ vars[project][type].source_url }}"
    dest: "{{ tmp_dir }}/{{ project }}"
    version: "{{ vars[project][type].version }}"
    force: true

- name: Build binary using cargo
  ansible.builtin.command:
    cmd: cargo cf-build-release
  args:
    chdir: "{{ tmp_dir }}/{{ project }}"
  changed_when: false

- name: Copy binary and shared library files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    remote_src: true
    mode: "0755"
  with_items:
    - { src: "{{ tmp_dir }}/{{ project }}/target/release/{{ node_service_default_binary_name }}", dest: "{{ node_bin_dir }}/{{ service_identifier }}" }
    - src: "{{ tmp_dir }}/{{ project }}/target/release/{{ node_cli_default_binary_name }}"
      dest: "{{ node_bin_dir }}/{{ node_cli_default_binary_name }}"
  notify:
    - Restart service
